version: '3.8'
services:
  amule:
    # image: ezjos/amule-web:latest
    build: docker/.
    image: amule-web:testing
    ports:
      - "80:4711"
      - "4712:4712"
      - "4662:4662"
      - "4672:4672/udp"
    environment:
      - PUID=5000
      - GUID=5000
      - WEBUI_TEMPLATE=AmuleWebUI-Reloaded
    networks:
      amule:
        aliases:
          - amule
    volumes:
      - ./data/conf:/home/amule/.aMule
      - ./data/incoming:/incoming
      - ./data/tmp:/temp
networks:
  amule:
